### PR TITLE
Dev 1

### PR DESCRIPTION
**Pull request by gmartin102**
Cumulative changes to remove cluster logic , removed fpu bootloader code and PLL control logic

### CODE REVIEW

**Comment by gmartin102** [comment]
Mike,
I have been debugging some watchdog stuff and an bouncing between my local linux Vivado build machine and the corporate linux simulation servers to work the changes out for the various flows I have been doing pushes and pulls from my local fork, but since there is an outstanding PR the CI runs every time.  I think its all fixed now except for the vendor stuff that hopefully Florian can fix, but I forget to rerun the listing/formatting stuff on all my intermediate changes (out script created files don’t format according to the rules and I need to rerun the formatting script after every Vivado build). Maybe I should add that into the makefile?.  Once this is done we should be must more stabile though,  I also found out how to fix my zero delay issue. — “+nospecify -seq_udp_delay 0.5ns” did the trick od xcelium.



On Jan 13, 2022, at 3:30 PM, Mike Thompson ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi @gmartin102<https://github.com/gmartin102> and @someshwar-ms<https://github.com/someshwar-ms>, thanks for this pull-request. I see that @someshwar-ms<https://github.com/someshwar-ms> is now covered by an ECA, thanks!

Unfortunately, the linting and formatting checks have failed. I do not know much about these, so I've requested @zarubaf<https://github.com/zarubaf> to have a look. In the meantime, @gmartin102<https://github.com/gmartin102>, if you know how to run the lint and formatting checks yourself, please fix up the errors and push in a fix for them.

**Comment by MikeOpenHWGroup** [comment]
> I think its all fixed now except for the vendor stuff that hopefully Florian can fix

The "vendor up-to-date" check failed.  AFAICT, this runs `util/git-diff.py` which checks that the "vendor" repositories we use (e.g. the PULP debug unit) are the expected versions.  This script uses GitPython which I know next-to-nothing about so I will not comment further.   @zarubaf can you have a look?

**Comment by MikeOpenHWGroup** [comment]
Thanks @zarubaf!  (I need to get a tutorial on this stuff from you.)
@gmartin102, the PR is now ready-to-go.  Please let me know if you'd like to either merge in dev-1 (see #209) or you can merge Florian's fix on top of your dev branch.

**Comment by gmartin102** [comment]
Already Merged and awaiting approval!

On Jan 14, 2022, at 12:36 PM, Mike Thompson ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Thanks @zarubaf<https://github.com/zarubaf>! (I need to get a tutorial on this stuff from you.)
@gmartin102<https://github.com/gmartin102>, the PR is now ready-to-go. Please let me know if you'd like to either merge in dev-1 (see #209<https://github.com/openhwgroup/core-v-mcu/pull/209>) or you can merge Florian's fix on top of your dev branch.

**Review by MikeOpenHWGroup — APPROVED** [review]

**Pull request merged**
