### PR TITLE
CORE_V_MCU high level design specs

### PR DESCRIPTION
**Pull request by cst-rameez**
Adding high level design specs for the IPs which have insufficient information in core_v_mcu user manual https://docs.openhwgroup.org/projects/core-v-mcu/

Following are CORE-V-MCU IP blocks whose documents are updated:
[APB Advanced Timer](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_adv_timer.html)
[APB SoC Controller](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_soc_ctrl.html)
[APB PLL Interface](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_fll_if.html)
[APB_GPIO](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_gpio.html)
[APB Timer](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_timer.html)
[ABP I2C Slave](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_i2cs.html)
[APB Event Control](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_event_cntrl.html)
[UDMA CAMERA Interface](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/udma_cam.html)
[UDMA SD Card Interface](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/udma_sdio.html)

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @cst-rameez, thank you for this tremendous contribution to the CORE-V-MCU User Manual.  It is much appreciated.  I am in the process of reviewing the technical content and will leave my comments here.  In the meantime there are two legal issues to resolve:
1. Please work with @DBees to ensure you are covered by the ECA.  This is most important - we cannot accept your contribution unless this is complete.
2. Please re-instate the comment headers for the RST files you are updating.  Here I will use `docs/doc-src/ip-blocks/apb_adv_timer.rst` as an example:
```
..
   Copyright (c) 2023 OpenHW Group

   SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
```
This is the License Header and it is a legal requirement that you maintain this.  Of course, your organization is making a significant contribution, so you can add that to the License Header like this:
```
   Copyright (c) 2023 OpenHW Group
   Copyright (c) 2024 CircuitSutra

   SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
```
The next few lines in the comment header are intended as a helpful guide for editors to illustrate how to create section headers.
```
.. Level 1
   =======

   Level 2
   -------

   Level 3
   ~~~~~~~

   Level 4
   ^^^^^^^
```
Lastly, this is a tag that can be used to create hyper-links between chapters, so it should remain.
```
.. _apb_advanced_timer:
```

**Comment by DBees** [comment]
@MikeOpenHWGroup @cst-rameez it appears the ECA is in good shape

**Comment by disdi** [comment]
Really nice work.

**Comment by MikeOpenHWGroup** [comment]
> it appears the ECA is in good shape

Really?  The Eclipse ECA Validation Service says, "There is no valid ECA on file for rameez.syed@circuitsutra.com." and the eclipsefdn/eca check in this PR's run-flow is still failing.

**Comment by DBees** [comment]
@cst-rameez my error. Can you please (as requested for the first pull request made to programs repo), log into your Eclipse Foundation Account and click the "I work for  an employer who is an Eclipse Foundation member" and identify your employer. That should clear it. If that doesn't work, can you please ping me and we can chat live.

**Comment by cst-rameez** [comment]
Hi @DBees, I have updated my profile. could you please check what could be the problem now?

**Comment by cst-rameez** [comment]
> Hi @cst-rameez, thank you for this tremendous contribution to the CORE-V-MCU User Manual. It is much appreciated. I am in the process of reviewing the technical content and will leave my comments here. In the meantime there are two legal issues to resolve:
> 
> 1. Please work with @DBees to ensure you are covered by the ECA.  This is most important - we cannot accept your contribution unless this is complete.
> 2. Please re-instate the comment headers for the RST files you are updating.  Here I will use `docs/doc-src/ip-blocks/apb_adv_timer.rst` as an example:
> 
> ```
> ..
>    Copyright (c) 2023 OpenHW Group
> 
>    SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
> ```
> 
> This is the License Header and it is a legal requirement that you maintain this. Of course, your organization is making a significant contribution, so you can add that to the License Header like this:
> 
> ```
>    Copyright (c) 2023 OpenHW Group
>    Copyright (c) 2024 CircuitSutra
> 
>    SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
> ```
> 
> The next few lines in the comment header are intended as a helpful guide for editors to illustrate how to create section headers.
> 
> ```
> .. Level 1
>    =======
> 
>    Level 2
>    -------
> 
>    Level 3
>    ~~~~~~~
> 
>    Level 4
>    ^^^^^^^
> ```
> 
> Lastly, this is a tag that can be used to create hyper-links between chapters, so it should remain.
> 
> ```
> .. _apb_advanced_timer:
> ```

Incorporated the following changes mentioned above.

**Pull request merged**
