### PR TITLE
Genesys2

### PR DESCRIPTION
**Pull request by gmartin102**
Changes to the Build scripts to support the Genesys2 FPGA board as an emulation target. Added  UART Srec boot capability to the bootloader.

### CODE REVIEW

**Review by jeremybennett — CHANGES_REQUESTED** [review]
@gmartin102 I started to test this using the Verilator model and it blew up:
```
$ make model-lib
fusesoc --cores-root . run --target=model-lib --setup \
	--build openhwgroup.org:systems:core-v-mcu | tee model-lib.log
INFO: Preparing openhwgroup.org:ip:apb2apbcomp:0
INFO: Preparing openhwgroup.org:ip:apb2per:0
INFO: Preparing openhwgroup.org:ip:apb_adv_timer:0
INFO: Preparing openhwgroup.org:ip:apb_fll_if:0
INFO: Preparing openhwgroup.org:ip:apb_gpio:0
INFO: Preparing openhwgroup.org:ip:apb_i2cs:0
INFO: Preparing openhwgroup.org:ip:apb_node:0
INFO: Preparing openhwgroup.org:ip:apb_timer_unit:0
INFO: Preparing openhwgroup.org:ip:axi_slice:0
INFO: Preparing openhwgroup.org:ip:cv32e40p:0
INFO: Preparing openhwgroup.org:ip:logint_dc_fifo_xbar:0
INFO: Preparing openhwgroup.org:ip:tcdm_interconnect:0
INFO: Preparing openhwgroup.org:ip:udma_camera:0
INFO: Preparing openhwgroup.org:ip:udma_core:0
INFO: Preparing openhwgroup.org:ip:udma_external_per:0
INFO: Preparing openhwgroup.org:ip:udma_filter:0
INFO: Preparing openhwgroup.org:ip:udma_i2c:0
INFO: Preparing openhwgroup.org:ip:udma_i2s:0
INFO: Preparing openhwgroup.org:ip:udma_qspi:0
INFO: Preparing openhwgroup.org:ip:udma_sdio:0
INFO: Preparing openhwgroup.org:ip:udma_uart:0
INFO: Preparing pulp-platform.org::common_cells:1.20.0
INFO: Preparing pulp-platform.org::tech_cells_generic:0
INFO: Preparing quicklogic.com:ip:efpga:0
INFO: Preparing openhwgroup.org:ip:l2_tcdm_hybrid_interco:0
INFO: Preparing pulp-platform.org::axi:0.28.0
INFO: Preparing pulp-platform.org::fpnew:0
INFO: Preparing pulp-platform.org::fpu_div_sqrt_mvp:0
INFO: Preparing pulp-platform.org::riscv_dbg:0
INFO: Preparing openhwgroup.org:systems:core-v-mcu:0
ERROR: Setup failed : Cannot find tb/mem_init_files/verilatorBoot.mem in :
	.
	.
```

**Comment by MikeOpenHWGroup** [comment]
This pull request has been reviewed by @gmartin102, @MikeOpenHWGroup and we believe it is good-to-go.

@jeremybennett can you confirm (or refute, as the case may be) that the current head of the Genesys2 branch resolved #212?

**Review by jeremybennett — APPROVED** [review]

**Comment by jeremybennett** [comment]
I can confirm that the software debug interface all works just fine. My review comments are now marked as satisfied.

Actually I was able to find a bug in the software. There is an issue with the Debug interface (see [#218](https://github.com/openhwgroup/core-v-mcu/issues/218)) but that does not hold up merging this work.

**Comment by MikeOpenHWGroup** [comment]
Thanks @jeremybennett. I'll merge this in.

**Pull request merged**
