### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by gmartin102**

### CODE REVIEW

**Review by MikeOpenHWGroup — COMMENTED** [review]
Hi @gmartin102, I do not recognize very many of the updates in this pull-request.  It appears that many recent updates to `dev` are being done via direct pushes from you without going through a pull-request.  Is that the case?

**Review by jeremybennett — APPROVED** [review]
I built the Verilator model against this branch and it had no regressions.

From this perspective, I'm happy to approve the commit. HOWEVER, this is the only check I have done!

**Comment by gmartin102** [comment]
Yes this was a direct update from my dev branch that I have been working on for sometime to remove all the dead cluster code.  We can talk more about it tomorrow

Greg

On Dec 14, 2021, at 11:52 AM, Jeremy Bennett ***@***.***> wrote:

﻿
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@jeremybennett approved this pull request.

I built the Verilator model against this branch and it had no regressions.

From this perspective, I'm happy to approve the commit. HOWEVER, this is the only check I have done!

**Comment by gmartin102** [comment]
@MikeOpenHWGroup , yes this was a large consolidated copy into a new dev branch of openhardware group.  it removes all the dead cluster code which was a rather large and difficult process to remove

**Comment by MikeOpenHWGroup** [comment]
> @MikeOpenHWGroup , yes this was a large consolidated copy into a new dev branch of openhardware group. 

Hi @gmartin102.  Such "direct pushes" to any of the OpenHW Group "CORE-V" repositories are frowned upon.  To add or modify code the update must be part of a pull-request and the pull-request must be reviewed by a Committer who is not also the person who issued the pull-request.   This applies to all branches of this repository, not just the master branch.

Having said that, a visual inspection of the code looks OK and given that @jeremybennett has regressed this code with his Verilator setup I will complete the merge.

Please, in future, all updates to any branch of this repo should be done via a pull-request, not a direct push.

**Pull request merged**
