### PR TITLE
update CORE-V-MCU Quick Start Guide for WLS2 users

### PR DESCRIPTION
**Pull request by davideschiavone**

### CODE REVIEW

**Review by MikeOpenHWGroup — COMMENTED** [review]
Thanks for this @davideschiavone.  With all the recent additions this "Quick Start Guide" is no longer so "quick", so I will probably decompose it into a series of targeted guides.   Nevertheless the additional you propose are good so I will merge them.

Before doing that, there is something to resolve.  GitHub is reporting that one of the RTL files is "unchanged with check annotations":
image
I have never seen this before (apparently it is a beta feature).  Any ideas what this means?

**Comment by davideschiavone** [comment]
> Thanks for this @davideschiavone. With all the recent additions this "Quick Start Guide" is no longer so "quick", so I will probably decompose it into a series of targeted guides. Nevertheless the additional you propose are good so I will merge them.
> 
> Before doing that, there is something to resolve. GitHub is reporting that one of the RTL files is "unchanged with check annotations": image I have never seen this before (apparently it is a beta feature). Any ideas what this means?

hi @MikeOpenHWGroup , no idea what it means... looking at my commit I only pushed the readme file... I feat that maybe previous commits may have broken this

**Comment by MikeOpenHWGroup** [comment]
OK, let me look at it.  Up to now I've been avoiding submodules and vendored components so now it is time to learn how to implement a patch file.

**Comment by davideschiavone** [comment]
@MikeOpenHWGroup I updated the dependecies for apt

**Review by MikeOpenHWGroup — APPROVED** [review]

**Pull request merged**
