### PR TITLE
adding citation

### PR DESCRIPTION
**Pull request by davideschiavone**

### CODE REVIEW

**Review by jeremybennett — APPROVED** [review]
Looks good to me. Thanks

**Comment by jeremybennett** [comment]
(I've reviewed, but this @gmartin102 's repo, so he has the final say)

**Comment by zarubaf** [comment]
I would suggest you make use of the (new) Github citation feature (maybe in addition to the README). https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Review by gmartin102 — APPROVED** [review]

**Comment by davideschiavone** [comment]
> I would suggest you make use of the (new) Github citation feature (maybe in addition to the README). https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

done @zarubaf

**Review by zarubaf — APPROVED** [review]
Awesome @davideschiavone

**Pull request merged**
