### PR TITLE
Latest (v0.0-3373-g54e37ed0) verison of Verible

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
The latest update to verible is changing the formatting of a lot of MCU files.  Please do not merge this unless/until the`Do Not Merge` label is removed.

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
@zarubaf, @gmartin102 

Following Florian's suggestion, I updated the version of Verible I use on my local machine and in the GitHub Actions of this repo to the latest pre-built version for Ubuntu 20.04 (v0.0-3373-g54e37ed0).  The good news is that this seems to work and now all Lint checks are passing.

The not-so-good news is that the latest version of Verible has significantly (?) different formatting rules than the current version we are using (v0.0-1051-gd4cd328) and 30 SystemVerilog files have been re-formatted.   I have little doubt that the new formatting is "better", but do we want to change that many RTL files given that we should be working to create a tag with _exactly_ what we released to CMC.

**Comment by zarubaf** [comment]
I think in principle that change is good and necessary as the tool evolves, so I would vote it in.

If the goal is just to produce the RTL Freeze state then obviously this isn't as good and we should probably waive the `verible` check for the failing commits. Agree?

**Comment by MikeOpenHWGroup** [comment]
> If the goal is just to produce the RTL Freeze state then obviously this isn't as good and we should probably waive the verible check for the failing commits. Agree?

Agreed.  So here is what I propose:
1. Waive the Verible checks for #314 from @gmartin102.  This will allow us to create a v1.0.0 for CORE-V-MCU that will match what we actually built.
2. After creating the v1.0.0 release, merge in this PR (or a version thereof) and that will start the ball rolling on the next release (not yet planned).

**Comment by zarubaf** [comment]
Agree, we can merge with the CI failing.

**Comment by MikeOpenHWGroup** [comment]
I managed to find the secret sauce to get the verible CI checks to pass.  See the README for details.

Merging it in...

**Pull request merged**
