### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by gmartin102**

### CODE REVIEW

**Comment by jeremybennett** [comment]
@gmartin102 Let me know when you have your branch ready and I'll try the Verilator model against it.

**Comment by gmartin102** [comment]
Jeremy,
Please test the openhwgroup/core-v-mcu dev branch when you have time. If it is ok, I will do a PR on the dev branch into the master
Greg


On Dec 13, 2021, at 8:27 AM, Jeremy Bennett ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



@gmartin102<https://github.com/gmartin102> Let me know when you have your branch ready and I'll try the Verilator model against it.

**Comment by jeremybennett** [comment]
@gmartin102 Tested, and no regressions with the Verilator model.

**Comment by MikeOpenHWGroup** [comment]
> Tested, and no regressions with the Verilator model.

Sorry @jeremybennett, I know you comment was not to me, but I did not catch your meaning there.  Did you mean, "no failures in regression with the Verilator model", or "no regression was run with the Verilator model"?   Or perhaps you meant something _completely_ different! :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
