### PR TITLE
Gam doc

### PR DESCRIPTION
**Pull request by gmartin102**
Updates to eFPGA interface document

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hey Greg, Eclipse is failing the ECA check for this PR.  Apparently you submitted this PR from an account associate with an email address of the form `gmartin102@****.****.****.com`.  Can you rebase or resubmit from your usual account?

**Comment by gmartin102** [comment]
Hmm, a little confusing that is my quicklogic github account which should be the one I’ve always used.  Is it possible my contributor status has lapsed?
Greg


From: Mike Thompson ***@***.***>
Date: Wednesday, June 28, 2023 at 2:40 PM
To: openhwgroup/core-v-mcu ***@***.***>
Cc: Greg Martin ***@***.***>, Author ***@***.***>
Subject: Re: [openhwgroup/core-v-mcu] Gam doc (PR #308)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hey Greg, Eclipse is failing the ECA check for this PR. Apparently you submitted this PR from an account associate with an email address of the form gmartin102@****.****.****.com. Can you rebase or resubmit from your usual account?

**Comment by DBees** [comment]
@gmartin102 your ECA status is valid

**Comment by DBees** [comment]
Greg it does seem to be an email address issue. Will email you

**Pull request closed without merging**
